### ISSUE TITLE
URL resolving issue

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#102]
When clicked on as a link from Slack, or when entered directly into the browser window, the following URL does not resolve on Chrome/Windows 7: https://plus.zakgroup.co.uk/en/explore?tag=peach-emoji

**Browser:** Chrome, 61.0.3163.100 (Official Build) (64-bit)
**OS:** Windows 7

However, when viewing on the site, e.g. accessed through the 'Explore' section, the URL does resolve. Not sure why this is happening. Unable to troubleshoot further.

**Comment by rdunk** [comment]
Good spot.

Basically the app makes two requests to the server on first load, one to get the site wide data and one for the specific page data. This error was happening when the server was returning the explore page data before the site data, as the app was trying to access tag information it didn't yet have.

Fixed in 65f78595eda933e97f1ae455a7d6d92edb3da797.
