### ISSUE TITLE
CDN: explore ways of making content load faster outside of HK

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#122]
Hi @rdunk -- as discussed logging this task here for investigation.

**Comment by rdunk** [comment]
@micahwalter this is probably one that you're best placed to answer. I know we discussed this briefly before. My main concern is with image assets at the moment, if a CDN could help cut down loading times for those I think that would be a huge help.

**Comment by chrismplus** [comment]
@micahwalter can you let @rdunk and I know what you think? If we're promoting the site globally it'd obviously be good that it's fast.

**Comment by chrismplus** [comment]
@micahwalter — 💭?

**Comment by chrismplus** [comment]
@micahwalter 🐧

**Comment by micahwalter** [comment]
OK - So we are still serving static assets ( images ) directly from the CMS server. To move this to a CDN we would need to do the following:

- [ ] Create an S3 bucket on AWS to store images.
- [ ] Copy all existing images to S3
- [ ] Create a CDN mirror of the S3 bucket with CloudFront
- [ ] Set the new CDN domain name somewhere in Processwire so it serves images from there instead of the CMS server.
- [ ] Set up the CMS server to sync newly added images to S3 upon upload.

The first three are pretty straightforward and I can do these on Friday. The last two will require some intervention from @rdunk. I imagine there is a Processwire plugin that can handle the last one, but I'm not familiar.

-micah

**Comment by rdunk** [comment]
Point 4 I imagine will be relatively straightforward to do. Point 5 is a little more involved, just due to the way Processwire generates image variants. I'm sure it's doable, dumping some reference links for myself here:

https://github.com/mirzadabeer/ManageImagesOnAmazonS3Bucket
https://github.com/nmendes/amazons3cloudfront

**Comment by micahwalter** [comment]
We could also just set up a cron job to sync with S3 every couple of
minutes or something ...

M

**Comment by chrismplus** [comment]
@micahwalter @rdunk — wanted to loop back and emphasise this issue. Been speaking to some people in Oz. Loading times are varying a bit, but when they're slow, they're really pretty slow. It would be great to look into this side of the website soon.

**Comment by rdunk** [comment]
@micahwalter Seems sensible that I try and implement this as a module in ProcessWire, would it be possible to set up an S3 bucket to test it with?

**Comment by chrismplus** [comment]
Hi @rdunk — can we get an update on the S3 bucket for testing? @micahwalter's in Hong Kong this week so good time to action this.

**Comment by chrismplus** [comment]
Hi @rdunk — I purchased ProCache (Single). Detail is in the email. Let me know whether you need anything else.

**Comment by rdunk** [comment]
Not sure I received the email—will catch up with you tomorrow on this one.

**Comment by rdunk** [comment]
@chris — All media assets are now being served via CloudFront. Seeing a significant improvement in load times in London, almost 10x faster. For example, a ~3MB image has gone from ~3000ms down to ~350ms.

@micahwalter is adding some further configuration so we can serve the font files via the CDN. Should be able to get that done tomorrow.

**Comment by chrismplus** [comment]
@rdunk @micahwalter — fantastic. Let me know how things go with the font files.

**Comment by micahwalter** [comment]
ok, I've done this for both production servers. I think you may just need to redeploy the site @rdunk .

**Comment by rdunk** [comment]
Great, fonts now being served by the CDN.
