### ISSUE TITLE
Load more: unexpected loading state

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#124]
Clicking the 'Load More' button under the "CONSERVATION TEAM" header on the homepage brings in the 4th tile (currently hidden behind the interaction) on the right of the screen instead of the left. 

**Viewport size:** 1321 × 1232px
**Browser:** Version 62.0.3202.94 (Official Build) (64-bit)
**Device/OS:** iMac, OS X El Capitan, Version 10.11.6

**Tile brought in on the right:** 
![image](https://user-images.githubusercontent.com/26731347/33015476-dfad397a-ce25-11e7-81bb-5277d6aaf8ea.png)

**Comment by rdunk** [comment]
The layout algorithm here tries to pack items under the shortest columns first to minimise the amount of vertical space the items occupy. So in this case the shortest column is the last one, so it appends the new item in that column. I'm not sure how we can avoid this without using a completely different layout algorithm.

**Comment by chrismplus** [comment]
Moving to backburner. Let's see how important this is in the greater scheme of things.

**Comment by chrismplus** [comment]
Could the algorithm be left-to-right?

**Comment by rdunk** [comment]
With a directional layout columns would no longer be balanced based on item or 'card' heights. We would have to enforce it so that the same number of items appear in each column (even though a journal issue might be one fifth the height of a journal article), this would result in some pretty strange looking layouts, e.g. with one column much longer than others.

**Comment by chrismplus** [comment]
Okay, let's leave it for now then.
