### ISSUE TITLE
Preview links

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#183]
@rdunk —

When inside the CMS you can view, in preview mode, an unpublished piece of content. You're taken to a URL and can view the page. However, when this link is sent to someone else, the page returns a 404 error. 

Case in point: the unpublished Podium article. It can be previewed but the link doesn't work once set. Can we keep this "preview" link available for **all** users who have it? This will be very handy in terms of facilitating workflows. 

The current publishing state is as follows: 
![image](https://user-images.githubusercontent.com/26731347/35722819-c40f4e5a-0832-11e8-92fd-58ddbd739aa1.png)

We believe we've had the ability to do this previously. Can you shed some light on this issue?

**Comment by rdunk** [comment]
@chrismplus I'm not sure I follow this one. If a page is published and hidden, you should be able to share the preview "View" tab URL with anyone, as long as it includes the preview parameter in the URL? The current Podium article I can see is both hidden and unpublished, which means currently nobody will be able to preview it.

**Comment by chrismplus** [comment]
@rdunk — yes—I've had to unpublish it to hide it from the Podium and Issue landing pages. If just "hidden" is checked, the article lists on these pages. 

When the article was in "Hidden" mode—the page was not viewable for preview—a 404 error appeared instead of the actual page.

**Comment by rdunk** [comment]
Hmm, both sound incorrect, I'll try and find out why this is happening.

**Comment by chrismplus** [comment]
Thanks @rdunk — as illustrated there are two issues here: 

1. Being unable to send preview links to people. 
2. 'Hiding' the article doesn't seem to work at the moment—it lists on Podium/Issue landing pages regardless of its status.

**Comment by rdunk** [comment]
With regards to point 2, had the hidden article been previously manually added to the "Recent Articles" list in the CMS? I've added an additional check so this shouldn't matter in future, but I imagine that's what the problem was.

With regards to preview links, I can't seem to replicate these not working properly at all. Provided they have the required "password" parameter at the end of the URL (i.e. copied **exactly** as the link appears when navigating from the View tab), they should work as intended for hidden, published pages.

**Comment by chrismplus** [comment]
Thanks, @rdunk —

unable to replicate preview link issue. Closing.
