### ISSUE TITLE
Include video content within sitemap.xml

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#201]
https://stories.mplus.org.hk/sitemap.xml

**Comment by chrismplus** [comment]
Could we loop in this parcel of work with the multi-lingual sitemap too?

**Comment by rdunk** [comment]
Looks like this one is easy to implement, will make the change alongside #210 as you suggest.

**Comment by rdunk** [comment]
Hey @chrismplus, I was working on implementing this but realised that no video content is actually hosted on the M+ servers. All the assets are hosted on Brightcove, YT, Youku etc. as far as I'm aware? I need to do a bit more research to work out how this sits with the sitemap, it is possible to include links to external assets but we don't necessarily have access to their URLs on the respective platforms, and I'm not sure if there are any associated drawbacks.

**Comment by chrismplus** [comment]
Yes, everything is hosted on Brightcove at the moment as far as M+ Stories is concerned. The aim for this additional sitemap is to ensure that video's being identified on the site as it is a major content stream. 

This schema seems to account for video being hosted externally? 
https://support.google.com/webmasters/answer/156442#videoobject

I also remember seeing this alternative to a video sitemap if that's of any help, or assists with the reasoning above: https://support.google.com/webmasters/answer/80471?hl=en

**Comment by rdunk** [comment]
Ah yes, looks like we can use a player URL instead of a direct media URL. Seems I can build the player links without having to make any Brightcove API requests (which the media links would require). I've made all the changes to get this working for Channel Episodes for now. Google requires at least four properties for <video> items to appear in the sitemap, for Episodes they are mapped like this:

`title` - uses the page title
`description` - uses the SEO description
`player_loc` - uses the Brightcove video ID given to generate the player URL
`thumbnail_loc` - uses the card image URL

It could get a bit complicated extending the sitemap to include videos from other platforms like YouTube, or to include all inline video content, as a title and description may not be immediately available without making a lot of API requests. The results would also probably need to be cached somehow.

Note: also holding off on pushing this one until staging issues are resolved.

**Comment by chrismplus** [comment]
Thanks @rdunk — noted.

**Comment by rdunk** [comment]
Available on staging now.

**Comment by chrismplus** [comment]
Hi @rdunk — I'm having trouble checking to see whether this has been updated via the XML. Can you send me a screenshot fo the four properties listed above from Staging?

**Comment by chrismplus** [comment]
Hi @rdunk – this looks like it's been deployed. Would like to confirm.
