### ISSUE TITLE
Auto-play video

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#217]
Hi @rdunk — we've been experimenting with the gyfcat platform to play looping video on our blogs; https://stories.mplus.org.hk/en/blog/yhchi-acquisition (scroll to end of post). They've recently changed the styling of their embedding however by adding a frame and pillar boxing the content. It made me think–we're already making extensive use of Brightcove... could we potentially use BC in the same way to replicate this functionality?

**Comment by rdunk** [comment]
Could well be possible. Not sure if there would be performance implications, I think Brightcove loads quite a lot of assets for a video player instance as it's pretty fully featured, I imagine gfycat is a more 'lightweight'.

Alternatively if gfycat allows direct linking to assets it could be easier to just create a gfycat module in the CMS instead of using an iframe so the styling would be customisable.

**Comment by chrismplus** [comment]
Thanks for the input @rdunk — I've spoken with Gfycat. It looks like they're going to make their iframes optional so we can leave this for the time being.
