### ISSUE TITLE
Image issue in CMS

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#218]
Hi @rdunk —

We've just stumbled across this strange issue in the CMS. We haven't come across this before. We were updating image file names in the CMS, clicked 'save', and the image previews disappeared from the CMS.

Screenshot: 
![image](https://user-images.githubusercontent.com/26731347/46528748-1c153880-c8c7-11e8-8450-c5bf1295aa35.png)

Do you have any idea what might have caused this? The images on the front-end of the site don't seem to be affected by this. 

CC: @ellenoredsson

**Comment by rdunk** [comment]
I'll loop in @micahwalter via Slack as I might need to take a look at something in the database. Seems all of the image variations correctly updated but the original file has perhaps retained its filename? Do you recall for this particular example what the filename was before it was changed?

**Comment by rdunk** [comment]
Okay, the problem was as I expected, the source image filename was not being updated but the variations were. As the original images aren't used at all by the frontend, only variations, the images were showing up fine for visitors.

Very strange as the permissions across all the image files are identical as far as I can tell. I've manually renamed the three affected files for that page so they should also show again in the CMS, but let me know if this crops up again and I'll try and find out exactly what causes it.

**Comment by chrismplus** [comment]
![image](https://user-images.githubusercontent.com/26731347/46594619-dd6dc100-cb06-11e8-95d6-0d5b97d364d5.png)
@rdunk — I've renamed the images in the CMS and there aren't any issues. We always rename the files once they're in the CMS. We'll keep an eye out for this issue. Will close ticket for now.
