### ISSUE TITLE
'Small' text size discrepancy 

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#228]
Refer to the unpublished article in Issue 1 of Podium. (Will have to preview through the CMS).

The size of the text under 'footnotes' and 'image notes' appear different; 'image notes' appears to render in a slightly larger size despite both markdown text fields having 'small text' selected. 

Let me know whether you have any difficulty in viewing this issue.

**Comment by rdunk** [comment]
I can't recall if this was intentional or not in the original designs, but footnote blocks use the 'extra small/xs' font size and normal text content blocks with the small text option enabled use the 'small/s' font size. You'll notice for example that the actual "Footnotes:" title text is the same size as the "Image notes:" title text, it's just the actual auto-extracted footnotes themselves that are smaller.

How would you prefer to resolve this? Introduce another option for extra small text or just make the existing small text use the "extra small" font size rather than the "small" font size?

**Comment by chrismplus** [comment]
I think it would be easiest to make the existing small text use the same size text as the footnote blocks.

**Comment by rdunk** [comment]
Done, ready to deploy this once I've got the OK on #229.

**Comment by chrismplus** [comment]
Thanks, @rdunk, all good.

**Comment by rdunk** [comment]
Great, this one is now deployed.
