### ISSUE TITLE
Alerts?

### ISSUE THREAD

**Issue by dianewang** [mplusmuseum/mplusmuseum-stories#260]
Can you help to review these @rdunk ? Placing in 'Ready' for your knowledge.

https://github.com/mplusmuseum/mplusmuseum-stories/network/alerts

**Comment by rdunk** [comment]
Hey @dianewang, only repository administrators are able to view alerts so I can't view these specifically, but I suspect they is due to a few dependencies we are using that are outdated. I see some alerts when I run a build on my local machine, nothing critical but good to fix regardless.

I need to move the app to use a newer version of something called webpack, which is basically the tool we use to compile everything from source code a production ready app. We are currently using version 3, and moving to version 4 is quite a complex process. I've done about 80% of the work required, but still a few things to resolve. I anticipate I'll have this done in the next few days and we should see alerts disappear.

I'll let you know when to check again so we can confirm.

**Comment by dianewang** [comment]
Thanks, Rupert. Confirming that there are no longer any alerts and closing this!
